### ISSUE TITLE
Covid19 Command for discord bot - province issue

### ISSUE THREAD

**Issue by Marloesske** [apex2504/python-corona-api#1]
when running the covid19 command, if try to identify a certain province of a country, such as, wuhan China, I run the command //cv china wuhan.
However I receive an error: the error is: 

`TypeError: _jhucsse() missing 1 required positional argument: 'province'`

as you can see I clearly placed the province, but for some reason it isn't picking it up.

**Comment by apex2504** [comment]
i can't reproduce this using the example cog. have you edited any of the code?

and just for reference, your comment says ` //cv china wuhan` which will not return any results anyway as the API does not provide such specific data.

**Comment by Marloesske** [comment]
Haven't changed anything appart from adding this after the time of last updated `corona_api.format_date(data.updated) + " UTC")` and changed color of embeds to `ctx.message.author.color`

**Comment by apex2504** [comment]
as you can see on [this line](https://github.com/apex2504/python-corona-api/blob/master/examples/discord_cog.py#L150), the `_jhucsse` method only executes when a `province` is provided, so it seems that there is something else that has been edited. 

regardless, i have updated the example cog to showcase some new features. before you make any of your own changes, please make sure the example provided works.

please try the new updated example cog.

**Comment by Marloesske** [comment]
Thanks for your help, it is working now!
